version: "3.9"
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testing
      MYSQL_USER: nam
      MYSQL_PASSWORD: nam123
    volumes:
      - ./data/mysql:/var/lib/mysql # chỏ dữ liệu trong docker qua thư mục ngoài data/mysql là thư mục trên local